version: "3.9"

services:
  frontend:
    # image: alkrauss48/simple-slides:dev-main
    # platform: linux/amd64
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "5173:80"
